apiVersion: "radix.equinor.com/v1"
kind: "RadixApplication"
metadata:
  name: "radix-testapp"
spec:
  environments:
    - name: "development"
      authorization:
      - role: "RadixAppAdmin"
        groups:
        - "g_radix_platform_user"
    - name: "production"
      authorization:
      - role: "RadixAppAdmin"
        groups:
        - "g_radix_platform_user"
  components:
    - name: "frexapp"
      src: "."
      ports:
       - 3000
      public: true